### ISSUE TITLE
back_inserter error

### ISSUE THREAD

**Issue by LionHackerman** [thesecretclub/window_hijack#3]
I keep trying to compile in Release and x64 but I get these two errors:
[Errors](https://cdn.discordapp.com/attachments/622603398755254272/782078014997004329/atea.PNG)

**Comment by GrigLog** [comment]
Add `#include <iterator>` to the beginning of the problematic file (dx_renderer.hpp).

**Comment by Fe1777** [comment]
It sounds like you have an issue labeled "back_inserter error" in the `window_hijack` repository managed by `S.C thesecretclub`. Let's walk through how you might troubleshoot and resolve this issue.

### Steps to Resolve "back_inserter Error" in `window_hijack` Repository

#### 1. **Clone the Repository** 

First, clone the repository to your local machine.

```sh
git clone https://github.com/thesecretclub/window_hijack.git
cd window_hijack
```

#### 2. **Create a New Branch**

It's always a good practice to work on a separate branch.

```sh
git checkout -b fix-back_inserter-error
```

#### 3. **Understand the Error Context**

Investigate where and how the `back_inserter` is used in the project. Commonly, this involves reviewing the relevant source code, documentation, or issue logs.

In a typical setup, the error might look like something related to STL or Boost library usage, such as:

```cpp
std::vector<int> nums;
std::fill_n(std::back_inserter(nums), 10, 0);
```

If there is any compile-time or runtime error related to `back_inserter`, it's often due to improper use or incorrect container management.

#### 4. **Check Container Initialization**

Ensure that the container meant to be used with `back_inserter` is properly initialized. For example:

```cpp
std::vector<int> nums;
nums.reserve(10); // Ensure there's enough space, if necessary
std::fill_n(std::back_inserter(nums), 10, 0);
```

#### 5. **Identify the Specific Error Message**

Run the project or the particular test cases to identify the exact error message.

```sh
# Assuming CMake or another build system
mkdir build
cd build
cmake ..
make
make test # if tests are available
```

#### 6. **Modify Source Code**

Adjust the source code where the error occurs. Here's a hypothetical example:

```cpp
#include <vector>
#include <algorithm>
#include <iterator>

int main() {
    std::vector<int> nums;
    // nums.reserve(10); // Uncomment if you need to reserve space in advance
    std::fill_n(std::back_inserter(nums), 10, 0);
    
    for(const auto& num : nums) {
        std::cout << num << " ";
    }

    return 0;
}
```

#### 7. **Run the Tests**

After making the necessary changes, rerun the tests or manually check to ensure the fix is effective.

```sh
make test
```

#### 8. **Commit and Push Your Changes**

After validating that your changes work as expected, commit the changes, and push them to the remote repository.

```sh
git add .
git commit -m "Fix back_inserter error"
git push origin fix-back_inserter-error
```

#### 9. **Create a Pull Request**

Navigate to your repository on GitHub, and you should see an option to create a pull request. Make sure to provide a detailed description of the error and how you fixed it.

**Example Pull Request Title and Description:**

- **Title:** Fix back_inserter error in vector initialization

- **Description:**

```
## Description
This pull request addresses the "back_inserter" error discussed in Issue #3.

## Root Cause:
The error occurred due to the improper handling of the container used with the `back_inserter`.

## Changes Made:
- Added proper initialization and resizing of the container before using std::fill_n with std::back_inserter.
- Ran the tests to confirm the fix.

## Type of Change:
- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes do not produce any new warnings.
- [x] I have added tests to validate that my fix is effective.
- [x] New and existing unit tests pass with my changes.

## Notes:
This fix ensures that the `back_inserter` can safely be used without causing runtime or compile-time errors.
```

#### 10. **Merge the Pull Request**

After submitting the pull request, it will go through the review process. Once the maintainers approve and merge it, your fix will be incorporated into the main codebase.

By following these steps, you can effectively troubleshoot and resolve the "back_inserter error" in the `window_hijack` repository.
